services:
  catalogdb:
    container_name: PostgresCatalog
    image: postgres
  
  basketdb:
    container_name: PostgresBasket
    image: postgres

  rediscache: 
    container_name: Redis
    image: redis
    
  catalog.api:
    container_name: CatalogApi
    image: ${DOCKER_REGISTRY-}catalogapi:${TAGC:-latest}
    build:
      context: Services/Catalog/Catalog.Api
      dockerfile: Dockerfile
      
  basket.api:
    container_name: BasketApi
    image:  ${DOCKER_REGISTRY-}basket.api:${TAGB:-latest}
    build:
      context: .
      dockerfile: Services/Basket/Basket.Api/Dockerfile

  discount.grpc:
    container_name: DiscountGrpc
    image: discount.grpc:${TAGG:-latest} 
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

volumes:
  postgres_catalog:
  postgres_basket:  

 